### ISSUE TITLE
hello_glfw color shifts as hmd rotates

### ISSUE THREAD

**Issue by remdragon** [cmbruns/pyopenvr#10]
I had to make some drastic adjustments to both hello_glfw and openvr.__init__.py to get the code working. Now I don't know if I broke something, I'm still new to the openvr API, but whenever I rotate the HMD, the colors of the cube walls shift.

I got hello_glfw from here:

https://github.com/cmbruns/pyopenvr/blob/master/src/examples/opengl/hello_glfw.py

I got openvr like so:

pip install openvr

Please see __init__.py.patch for the changes I made to openvr.__init__.py

hello_glfw2.py is the modified version of hello_glfw.py, hello_glfw.py.patch is the changes I made between the two. note I tweaked the color formula trying to troubleshoot the color shifting

Also worth noting, if I set the cube walls to just be red, it mostly stays red, but in certain orientations turns gray ( or maybe disappears? )

Finally, the play area boundaries flicker, not sure what might be causing that?

[hello_glfw.zip](https://github.com/cmbruns/pyopenvr/files/301952/hello_glfw.zip)

**Comment by remdragon** [comment]
I realized what's available via pip might not be the latest in git, so I grabbed the files from git and copied everything from the src/openvr folder into C:\Python27\Lib\site-packages\openvr\

I then re-ran hello_glfw.py unmodified from git and I still had to fix line 156 to this:

        self.texture.handle = ctypes.cast ( int(self.texture_id), ctypes.c_void_p )

That's the only change I have to make to get it running, but now I'm having a different problem. The hmd tracking orientation is completely off and there's weird near clipping going on. It looks kinda like the problem you get when multiplying a matrix the wrong way.

**Comment by cmbruns** [comment]
The pyopenvr bindings are still very much a work-in-progress. I myself just got the hello_glfw cube working a few days ago. I recognize there are strange problems with the matrices. I won't have an opportunity to work on this for at least a week though.

**Comment by remdragon** [comment]
Not a rush, I'm wanting to write code for my vive, but honestly I have more important projects I have to be working on right now. I'll keep tinkering and if I figure something out I'll let you know. If it helps, pink world doesn't seem to have nearly as many problems, but the distortion seems incorrect, because the play boundary warps and bends as you move around. Also, the boundary still flickers and the scenery does still occasionally disappear.

**Comment by remdragon** [comment]
okay, pink_world's issues were apparently temporary syncing issues with the Vive ( sorry, I'm still learning this thing ), but I believe I have found the bug in hello_glfw.py.

Specifically, matrixForOpenVrMatrix's 4x3 matrix initialization is backwards and should be this:

    elif len(mat.m) == 3: # HmdMatrix34_t?
        result = numpy.matrix(
                ((mat.m[0][0], mat.m[1][0], mat.m[2][0], 0.0),
                 (mat.m[0][1], mat.m[1][1], mat.m[2][1], 0.0), 
                 (mat.m[0][2], mat.m[1][2], mat.m[2][2], 0.0), 
                 (mat.m[0][3], mat.m[1][3], mat.m[2][3], 0.1),)
            , numpy.float32)  
        return result.I

With that change, there is now a very small box on the floor in the center of the play area and all the tracking is very nice. I blew the box's size up to 1.0 and then 5.0 and all the tracking still looks fantastic

**Comment by cmbruns** [comment]
Great work getting this working. I'm unsure whether I have the same change in my working copy back home. As I recall, I was stuck on a problem where the matrices seem to behave differently between python 2 and python 3. I'll probably work on this more next week. What version of python are you using?

**Comment by remdragon** [comment]
I am getting good results with the following versions of Python ( both obtained from https://winpython.github.io/ ):

2.7.10
3.5.1

The reason I use WinPython is I have a lot of clients still running older versions of Windows and their 2.7 build generates executables that work even when built from Windows 10.

I have not tested with any builds from python.org, but I can't imagine it would make a difference.  You obviously have to make sure that the same version of openvr is installed in both versions of Python.

Is hello_glfw your code? I'd like to propose some enhancements to it and then use it as a frame-work for my current project. Specifically I have already added logic to handle window size changes, and I want to add support for optionally rendering the controllers and base-stations. I also want to add some button-handling logic which will generate some simple visual feedback in the display. I can implement these things as additional Actors in keeping with the current design of hello_glfw.

The way I intend to use it as a framework is something like you see below, that way as the pyopenvr API is modified to be where it needs to be and the hello_glfw code is enhanced, it will minimize the changes that need to be made to my project:

# my-project.py

from hello_glfw import *

class MyActor(BasicGlResource):
    ...

if __name__=='__main__':
    actor0 = MyActor()
    renderer0 = OpenVrGlRenderer(800, 600, actor0)
    with GlfwApp(renderer0, "My Project") as glfwApp:
        glfwApp.run_loop()

**Comment by cmbruns** [comment]
@remdragon Yes, I wrote hello_glfw. Further, I began sketching out those OpenVrGlRenderer and GlfwApp classes, with the intention of eventually making them importable as helper classes somewhere under the openvr package. I'm pleased to see that you have anticipated this usage.

I'm hoping to work more on pyopenvr very soon now. Especially since openvr 1.0.1 just came out.

**Comment by remdragon** [comment]
I have written a hello_wx.py and hello_sdl.py that both use the corresponding frameworks and are otherwise practically identical. The one difference is I renamed GlfwApp to HelloApp so I can switch from one framework to another while testing the code. I would be happy to donate these to the pyopenvr project. The reason I created them is I was troubleshooting an issue I was having with font renderering. Apparently opengl core 4.1 doesn't like glGenLists. Anyway, if you like having those other framework interfaces, it might be best to separate out the openvr-specific stuff into it's own file so it's not duplicated between the 3 examples.

I have basic font rendering working based on nehe lesson 43. I've been studying the Valve paper on text rendering and wrote some code to generate a distance field that I believe is fairly efficient by adapting a path-finding algorithm for the purpose. If I can get this code to a state I'm reasonably happy with, I'd be happy to contribute them as well.

I have also been studying the hello opengl code in the openvr sdk samples to see how to render the controller models. It looks fairly straight-forward and I'd like to get that into the hello framework as well. Looking at the structure of your code, there should probably be a dedicated Actor for that purpose.

**Comment by cmbruns** [comment]
I created the GlfwApp class to hold all of the glfw specific code, and envisioned eventually creating analogous additional classes like GlutApp, QtGlApp, PyGameApp, SdlApp, OpenSceneGraphApp, etc., to help folks get started with whichever python graphics framework they want. Rather than renaming GlfwApp and generalizing it, I would prefer if you could create separate classes for those other frameworks, satisfying, if possible, the same interface.

And I intended the OpenVrGlRenderer class to contain all the code specfic to OpenVR. I don't necessarily have specific plans to create other analogous classes such as OsvrGlRenderer and OculusVrGlRenderer, but maybe eventually, right?

I'd like the various "Actor" classes we create to be in pure OpenGL, if possible, without making explicit references to OpenVR nor glfw nor sdl etc.

Now that you are thinking about using these separate classes, I'd like to begin thinking about where to place them in the openvr package. I don't believe "Hello" is the correct namespace for these concepts.

**Comment by remdragon** [comment]
For testing purposes, I like the idea of being able to switch from one framework to another by changing only the import line, but in the interest of working together, I can certainly live with your naming conventation for the App classes.

Vive/Oculus specific classes may eventually be necessary, but that's a bridge we can cross when we get there.

The following is intended with the utmost respect... I don't see a problem with a Hello namespace, depending on the goal. If we're just providing some very easy to understand code that shows how to really get up and running in openvr, I think Hello is perfectly fine. If your plan was to build a production-quality framework, that is a very different goal which mayl require different design decisions. The samples folder of the openvr project might not be the best place for it to live?

Would you like copies of my wxPython and SDL framework implementations? I can attach them to a post in this tracker, or how else would you like them?

**Comment by cmbruns** [comment]
You might still be able to change only the import line with more complex statement like
`from openvr.glfwapp import GlfwApp as HelloApp`

Yes, I definitely would like to incorporate your wxPython and SDL implementations. Easiest for me would be for you to fork this pyopenvr github project and put your work where you think it should be. But if it's easier for you to attach source files to this thread that's fine too.

**Comment by remdragon** [comment]
I don't quite understand how git works. I guess I'm going to have to learn sooner or later. Old-school SVN guy here ;)
[hello_apps.zip](https://github.com/cmbruns/pyopenvr/files/313008/hello_apps.zip)

**Comment by remdragon** [comment]
I thought about doing a rename on import, but that doesn't work well at the moment because you'll need a 2nd import to bring in OpenVrGlRenderer. However, if we're going to import that from a different file anyway ( I hope so ), then that won't be an issue any more.

**Comment by cmbruns** [comment]
@remdragon Thanks for those example files. I incorporated them and rearranged many files. I think I took into account most of your innovations. Except I did not keep this cast you added:

`self.texture.handle = ctypes.cast ( int(self.texture_id), ctypes.c_void_p )`

I see no error without the cast. What exact error prompted you to insert this cast?

**Comment by cmbruns** [comment]
The matrices seem to be working well now in both python 2 and python 3, using the transposition recommended by @remdragon, along with re-packing the view matrices immediately before use. So I'm closing this issue because the "title" problem is resolved. Other issues discussed in the comments should be opened as new issues if problems remain.

**Comment by cmbruns** [comment]
In particular, the matrix problems were fixed in revision a136ab59064edb263d661ba829e6311ec8bf2196
So this issue is closely related to #9
