### ISSUE TITLE
Tracking data - documentation of values

### ISSUE THREAD

**Issue by annn27** [cmbruns/pyopenvr#21]
We tried the code example given, which updates and prints the tracking data again and again. To use the data, we would like to know, which value belongs to which tracking parameter. We tried to find a documentation about that, but could find something so far.

Any help is appreciated  :)

**Comment by cmbruns** [comment]
It is outside the scope of this pyopenvr project to provide more documentation than exists in the main OpenVR project itself.

The class member TrackedDevicePose_t.mDeviceToAbsoluteTracking has the type HmdMatrix34_t. You can read the documentation, such as it is, for this class by typing at the python prompt
`>>> help(openvr.HmdMatrix34_t)`

**Comment by annn27** [comment]
Thanks for the quick reply. Sure, it should be part of the openvr documentation, but there I couldn't find a detailed description. So I hoped to find an answer here. 
I also read the help(openvr.HmdMatrix34_t), but it did not really give me the information I am looking for. We already figured out the position values x, y and z. 
But we find it hard to extract the headorientation from the other values.
So, if somebody knows more about that, we would be happy to understand. 
But thank you so much, anyway.

**Comment by awesomebytes** [comment]
This is super old, but just in case anyone is struggling with this, this piece of code:
https://gist.github.com/awesomebytes/778d4a1720a0ec3af2086ff6a0b057c3

Can do the job. I use it in this ROS package to publish the transformations and the controller state: https://github.com/uts-magic-lab/htc_vive_teleop_stuff/blob/master/scripts/vive_tf_and_joy.py
