### ISSUE TITLE
args to getControllerState

### ISSUE THREAD

**Issue by daniel5gh** [cmbruns/pyopenvr#27]
Hi,

I wanted to get the controller's state and saw I need to pass the size of the to-be-filled struct on the python interface.

Looking at the history I see [this](https://github.com/cmbruns/pyopenvr/commit/e4c5b938fbdc2b0d1e443f2e5dbc35bae59b31e5#diff-5291655d6f0d90db61a5402d95c0e6b2L2027) commit, which seems relevant but it doesn't have (or previously had) the situation as I'd expected.

What I expect is a `sizeof` determining the size instead of having to pass it manually. I patched the two getControllerState functions in [this](https://github.com/daniel5gh/pyopenvr/commit/7948bc60a448221e28fe0da747ff226a44e615a4) commit on my fork.

I verified by passing 0 as size, which resulted in no data filled into the passed struct.

Using the `sizeof` works as expected, but is it the correct solution? If correct I can make a PR or you can just copy paste.

Thanks!

**Comment by cmbruns** [comment]
I'm uncertain whether this is the correct solution. But if it's working for you that seems good enough to me. I cannot find any documentation about this recent change to the OpenVR API.

**Comment by daniel5gh** [comment]
I couldn't find any documentation about this change either. Out of curiosity I just looked at the C# bindings and I noticed the following comment on this [line](https://github.com/ValveSoftware/openvr/blob/70acfe9262290ddb789588a7390e5fc60bb20080/headers/openvr_api.cs#L1626):
```
// This is a terrible hack to workaround the fact that VRControllerState_t was
// originally mis-compiled with the wrong packing for Linux and OSX.
```
This explains the need to size on the API. It's been added in version 1.0.4 in [this](https://github.com/ValveSoftware/openvr/commit/84e877f1e099173378759189609b90870f422130#diff-1aed950f5e3868e2a73cdbd7ba439a2bR1487) commit.

Any suggestions on this, is does `translate.pl` need to be aware of this?

**Comment by cmbruns-hhmi** [comment]
Nice work finding that comment!

Ideally we should add a rule to translate.pl to catch this situation. But because I don't have much time to look at this now, it would be OK to manually patch __init__.py, with a big "TODO" comment, like I did in several other places where I manually carry forward edits into subsequent releases.

If you'd like to take a crack at patching translate.pl yourself, it would be nice to first search the API to see if there are any other method arguments in this same category.

Also now I'm suddenly worried about the correctness of structure packing in pyopenvr. ctypes.Structure has the ability to explicitly specify packing, but I have not used any of that in pyopenvr. I have only been testing on 32-bit Windows so far, and that seems to be working OK. But I'm concerned that 64-bit or Mac or Linux might have packing problems.

**Comment by daniel5gh** [comment]
Thanks!

I will take a look at `translate.pl` somewhere this week probably. If I think it's too much effort I will, for now, amend my patched `__init__.py` with "TODO" comments as you suggested and make a PR.

Regarding the structure packing on other platforms, I currently can only test on 32 and 64 bit windows, so far I worked with 32 bit windows. Looking further at the C# bindings I see
```C#
// This structure is for backwards binary compatibility on Linux and OSX only
[StructLayout(LayoutKind.Sequential, Pack = 4)] public struct VRControllerState_t_Packed
```
which indicates that (previous) versions on those platforms where forced to align on 4 byte boundaries. AFAIK the default compiler behavior is to align on the size of the largest field. In this case that would be 8 bytes, which was the case for me yesterday because I saw a `sizeof` of 64.

The "normal" struct in C# is defined like this:
```C#
[StructLayout(LayoutKind.Sequential)] public struct VRControllerState_t
```
where it is using the default packing, similar to how `ctypes` would pack structures if no explicit `_pack_` is given. So I think pyopenvr should be good on other platforms, except for the specific case where versions of libs have `VRControllerState_t` that are explicitly packed on 4 bytes. If this is true then pyopenvr would ideally need a similar hack as is done in the C# bindings. I don't have much experience with these kind of things, not can I test any of this. Also if I understand it correctly this would only be a problem if someone is using an older version of the libs, in which case upgrading could be a fix.

**Comment by cmbruns-hhmi** [comment]
Another approach to patching this would be to include a default argument value, like

```python
def getControllerStateWithPose(self, eOrigin, unControllerDeviceIndex, unControllerStateSize=sizeof(VRControllerState_t)):
    ...
```

**Comment by daniel5gh** [comment]
What about something like this in `translate.pl`?
```perl
# exception for size parameter in GetControllerState
if ($fn_name =~ m/^getControllerState(WithPose)?$/) {
    for (my $index = 0; $index <= $#call_arg_names; $index++) {
        $call_arg_names[$index] =~ s/(unControllerStateSize)/$1=sizeof(VRControllerState_t)/;
    }
}
```

**Comment by cmbruns-hhmi** [comment]
Those look alright to me. Especially if you have tested to ensure that they create the code you expect.

**Comment by kazoo-kmt** [comment]
The latest opener_api.cs code (https://github.com/ValveSoftware/openvr/blob/bcac1bfbe2be3c1ff37e4f62b8e412fcdf29248e/headers/openvr_api.cs#L1656) says the following.
```
// This is a terrible hack to workaround the fact that VRControllerState_t and VREvent_t were
// originally mis-compiled with the wrong packing for Linux and OSX.
```
Does this mean we also have an issue for VREvent_t, not only VRControllerState_t?

**Comment by daniel5gh** [comment]
It appears that in the 1.0.7 release the C# bindings added that "Terrible hack" for `VREvent_t` as well. You could try adding size https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py#L4085
similar to https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py#L2219

This makes sense when looking at https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py#L3633, it expects the last parameter to be an uint.

So the current code will probably keep that size at 0, making the native code not fill the struct at all. This was the case with `getControllerState` when I was looking at it.

Considering the comment in C# binding say "were originally mis-compiled", if you are using one of these mis-compiled versions, this fix may not be enough and if that's the case you'll need to do some manual unpacking like is done in the C# bindings.

**Comment by kazoo-kmt** [comment]
Thank you for your comment. As I posted here (https://github.com/cmbruns/pyopenvr/issues/35), there is an issue that `VREvent_t` doesn't contains the correct value. 

> Considering the comment in C# binding say "were originally mis-compiled", if you are using one of these mis-compiled versions, this fix may not be enough and if that's the case you'll need to do some manual unpacking like is done in the C# bindings.
I'm using the latest release of pyopenvr (PyOpenVr version 1.0.0801). Does this mean I still need to change the file other than __init__.py? (such as openvr.h, openvr_capi.h and translate.pl)

**Comment by daniel5gh** [comment]
I was looking at the wrong function in `__init__.py` in my reply from earlier today.

Now upon more careful inspection I see that the `pollNextEvent` method is already passing the struct's size to the native code: https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py#L2180 This was already in place even before I added this fix for `getControllerState(WithPose)`

You don't have to patch it yourself. The issue you describe in #35 is not due to the same this issue (#27). If is was you would not even get a value for `eventType`, but you get 200. My bet at the moment is that the scruct is indeed packed on 4 bytes (on linux and osx), but the ctypes struct uses 8. I don't have much experience with this and I can not currently test on linux or osx either.

**Comment by kazoo-kmt** [comment]
Thanks a lot. I need to look more, but as for the quick check, when I insert `_pack_ = 4` at https://github.com/cmbruns/pyopenvr/blob/d745b6d/src/openvr/__init__.py#L1763 before `_fields_`, the returned value includes the correct `VREvent_Data_t`.
