### ISSUE TITLE
Consider using pkgutil, instead of __file__

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyopenvr#3]
https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py#L18

https://www.reddit.com/r/Vive/comments/4iy1fr/new_python_bindings_for_vive_openvr_developer_sdk/d32aqyq

**Comment by cmbruns-hhmi** [comment]
I think shared libraries like OpenVR might NEED to be loaded from a regular file. So this is one instance where pkg_resources/pkgutil might not be better than __file__.
