### ISSUE TITLE
VRClientDLLNotFound

### ISSUE THREAD

**Issue by claytmcneil** [cmbruns/pyopenvr#30]
When trying to run the example hello.py, I get the following issue:

OpenVR test program
Runtime is installed
Traceback (most recent call last):
  File "hello.py", line 15, in <module>
    vr_system = openvr.init(openvr.VRApplication_Scene)
  File "/usr/local/lib/python3.6/dist-packages/openvr-1.0.701-py3.6.egg/openvr/__init__.py", line 4973, in init
    initInternal(applicationType)
  File "/usr/local/lib/python3.6/dist-packages/openvr-1.0.701-py3.6.egg/openvr/__init__.py", line 5077, in initInternal
    _checkInitError(error.value)
  File "/usr/local/lib/python3.6/dist-packages/openvr-1.0.701-py3.6.egg/openvr/__init__.py", line 4959, in _checkInitError
    raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
openvr.OpenVRError: b'VRInitError_Init_VRClientDLLNotFound' (error number 102)

I did some poking at the OpenVR API and it seems like its looking for vrclient.so, which does exist at this path:

~/.local/share/Steam/steamapps/common/SteamVR/tools/bin/linux64

The API seems to support a VR_OVERRIDE environment variable. I tried setting it and got the same result. Checking strace, it looks like the vrclient.so is getting opened.

Probably user error, but I'm stuck and would appreciate any help.

**Comment by cmbruns** [comment]
I'm not sure anyone has really got pyopenvr working on linux yet.
Have you got non-python vr applications working on your computer?

**Comment by claytmcneil** [comment]
I got far enough to see the SteamVR compositor running and verify the HMD was tracking, but nothing on the screen. What I'm trying to do doesn't need and HMD so I didn't pay attention to making that work. Looks like the distro I'm using has a kernel which the prerequisite nvidia drivers don't support.

I'm going to try an older version and give everything a go. I'll report back.

**Comment by claytmcneil** [comment]
Alright, so I got SteamVR working (for the most part). I'm still getting the same error when launching a script though. 

Is anyone else interested in seeing this work on Linux besides me? I'm willing to do some work but I'd likely need support.

**Comment by cmbruns-hhmi** [comment]
@claytmcneil I searched for "linux" in this git repo and found some relevant discussions about getting linux working in issues #5 #22 and #26 . See especially the comments by @nemanja-rakicevic @mungewell @eric-schleicher @abencomo

Perhaps you could create a new page on the wiki https://github.com/cmbruns/pyopenvr/wiki to share and accumulate wisdom about getting pyopenvr working on linux.

**Comment by eric-schleicher** [comment]
Yes that would be great!  I have not ben successful getting pyopenvr running on ubuntu 16.04.  would love that.

**Comment by claytmcneil** [comment]
Ok, maybe stupid question. How is libopenvr_api_64.so built? Where's the source / Makefile for it?

**Comment by eric-schleicher** [comment]
I believe it ships as part of the steam client and that the source is not available

**Comment by claytmcneil** [comment]
Actually, I'm pretty sure its built from this project: https://github.com/ValveSoftware/openvr

I cloned it and attempted to build following the instructions but no luck initially. If someone has built this for Linux, let me know; otherwise I'll have to mess with it.

My plan is to build the lib with some debug in it to figure out why we're crashing.

**Comment by claytmcneil** [comment]
Ok, think I figured out how to build it. Just need to take some time and debug.

**Comment by claytmcneil** [comment]
Got it working. Confirmed that it can work on Linux.

**Comment by eric-schleicher** [comment]
Awesome eagerly awaiting being able to run this on linux!  many thanks

**Comment by cmbruns** [comment]
@claytmcneil Are you saying that by recompiling libopenvr_api.so yourself you got pyopenvr working?

Are you also using Ubuntu 16.04, like @eric-schleicher  is?

**Comment by claytmcneil** [comment]
@cmbruns Yes, I'm running on Ubuntu 16.04.

Recompiling libopenvr_api.so isn't the fix, but it did allow me to add some additional error information that allowed me to track it down.

The root problem is that the method of loading shared objects doesn't allow you to add a path at run time. The first instance of this causing problems is when loading libopenvr_api.so itself - I fixed that by adding an absolute path.

Problem is that there are several more libs that the vrserver needs to access and since the path setting isn't working, they weren't being found. Once I symlinked them all, I was able to run the tracker_test.py example.

**Comment by claytmcneil** [comment]
@eric-schleicher Do you have SteamVR working on Linux?

**Comment by cmbruns** [comment]
The recent activity here has prompted me to upgrade my old broken linux partition to Ubuntu 16.04, so I can participate in this momentum. I've just now got SteamVR working on linux, so I'm just about to begin to investigate these library issues too.

**Comment by cmbruns** [comment]
Thanks the the valiant efforts of @claytmcneil I too have made some progress. I combined those reports with some calls to ldd, to investigate library dependencies.

After I got steamvr installed and sorta working, I found I needed to install the following packages: 
- libudev-dev
- libvulkan-dev
- libsdl2-dev

Further, I needed to symbolically link libudev.so.1 to libudev.so.0; apparently steam vr uses an older version of that library.

I set my LD_LIBRARY_PATH to 

> /home/cmbruns/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/cmbruns/.local/share/Steam/steamapps/common/tools/bin/linux64:.

Notice the dot at the very end. With the LD_LIBRARY_PATH thus set, I was able to load "libopenvr_api.so" in \_\_init\_\_.py

Then to get the more advanced pyopenvr demo test_obj.py working I installed python modules
- numpy
- pyopengl
- glfw

and packages
- libglfw3-dev

The performance is not great. But its working for me now. But only when steamvr is already running. And I can't seem to launch steamvr from steam anymore. I have to try to run a pyopenvr script first, which fails, but causes steamvr to launch. Then, on the second attempt, when steamvr is running, the script succeeds.

**Comment by claytmcneil** [comment]
Glad to hear I'm not crazy! Yes, SteamVR is a bit of a mess at the moment. When you say can't launch from Steam, I assume you mean can't click the "VR" box in the upper right corner? If so, that seems to indeed be broken although launching from the SteamVR page (clicking the 'Play' button) works. Pairing Controllers and Resetting the Device causes crashes as well.  

I'd also recommend launching outside of Steam (that's how I do it).

As for the libs you mentioned, I symlinked to the ones provided by Steam, not sure if that's preferred or not.

What do you mean when you say performance isn't great? I haven't started the actual development I planned, so I'm curious about potential pitfalls.

**Comment by cmbruns** [comment]
Even clicking the 'Play' button gives a weird error for me most of the time when trying to launch steamvr on linux. There's some weird stuff going on.

By not-great performance I mean that the the frame rate is low enough to make me a bit ill with even a rather simple OpenGL scene. The SteamVR-for-linux project warns that "OpenGL applications are currently too slow to use interactively", so I was not surprised. They recommend using vulkan, which I do not have time to learn at the moment.

I'd say we are still quite far off from the time when a less heroic linux user will be able to simply 'pip install openvr' and start building vr worlds.

**Comment by claytmcneil** [comment]
Oh, I got it! Yeah, unfortunately I agree that we're a ways off from that. 

However, its prime time for some Lighthouse tracking with Linux!

**Comment by eric-schleicher** [comment]
> @eric-schleicher Do you have SteamVR working on Linux?

Yes.  I have it running

Also @claytmcneil  It's been noted (on the openvr sdk github) that you can't launch steamvr from the titlebar.    The best way i found to get it started was to kick it off from Library->Tools->SteamVR from the Steam Client.

**Comment by kazoo-kmt** [comment]
Continued from https://github.com/cmbruns/pyopenvr/issues/5#issuecomment-310455839. I got the exactly same error as this issue (VRClientDLLNotFound). My current LD_LIBRARY_PATH is as follows though still having no luck. :
```
$ echo $LD_LIBRARY_PATH
/home/user-name/venv/lib/python3.5/site-packages/openvr:/home/user-name/.steam/steam/steamapps/common/SteamVR/bin/linux64:/home/user-name/.steam/linux64:/home/user-name/.steam/steam/steamapps/common/SteamVR/tools/bin/linux64:/home/user-name/.steam/ubuntu12_64:.
```
In the above discussion, @claytmcneil and @cmbruns said they installed missing package into Linux as well as symlinked some libraries. How can I check which package is missing for Linux or which libraries should be symlinked?

**Comment by claytmcneil** [comment]
@kazon-kmt Did you look at the list  @cmbruns provided above?

**Comment by kazoo-kmt** [comment]
Yes, you are right! I installed all three packages mentioned and then simulinked. Not it seems working. 

```
(venv) user-name@user-name:~/pyopenvr/src/samples$ sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
(venv) user-name@user-name:~/pyopenvr/src/samples$ python hello.py 
OpenVR test program
VR head set found
Runtime is installed
b'/home/user-name/.steam/steam/steamapps/common/SteamVR/'
(1512, 1680)
1
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
[[1.0, 0.0, 0.0, -0.030949998646974564], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.014999999664723873]]
```

**Comment by claytmcneil** [comment]
I think you meant "now" instead of "not". If so, great to hear!

**Comment by DanielArnett** [comment]
Thank you all for this discussion. If anyone else comes across this thread: this command did the trick for me on Ubuntu 14.04:
`sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0`

[I also made a tutorial on how to use the trackers without the headset on Ubuntu.](https://gist.github.com/DanielArnett/c9a56c9c7cc0def20648480bca1f6772)
