### ISSUE TITLE
glfw init problem

### ISSUE THREAD

**Issue by amichlee** [cmbruns/pyopenvr#31]
I am unable to run glfw sample scripts due to an init problem. I am using python 3.6 32 bit on Windows 10
Here is the error I am receiving: 

```C:\src\pyopenvr\src\samples\glfw>python hello_glfw3.py
Traceback (most recent call last):
  File "hello_glfw3.py", line 17, in <module>
    with GlfwApp(renderer, "glfw OpenVR color cube") as glfwApp:
  File "C:\python36\lib\site-packages\openvr\glframework\glfw_app.py", line 90, in __init__
    super(GlfwApp, self).__init__(renderer=renderer, title=title)
  File "C:\python36\lib\site-packages\openvr\glframework\glfw_app.py", line 23, in __init__
    if not glfw.init():
AttributeError: module 'glfw' has no attribute 'init'

**Comment by cmbruns** [comment]
There are a few different glfw modules for python. I suspect you and I are not using the same one.

**Comment by godber** [comment]
I just did `pip install glfw` and this worked for me.

@cmbruns Would you like me to add dependencies to the `setup.py` file?  Maybe as an `extras_require` or something like that ([ref](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies))?

Then in the future people could install the window toolkit of choice with `pip install pyopenvr[glwf]`.

**Comment by cmbruns** [comment]
@godber is it too late to take you up on your offer to create a patch for setup.py?

**Comment by godber** [comment]
Maybe not, let me see if I can find some time this weekend.
