### ISSUE TITLE
Trigger axis value is always 0

### ISSUE THREAD

**Issue by mdovgialo** [cmbruns/pyopenvr#32]
As far as I understood trigger position should be inside of pControllerState as one of the axis.

But when I run this program:
```
import openvr

openvr.init(openvr.VRApplication_Background)

while True:
    print()

    result, pControllerState, pTrackedDevicePose = openvr.VRSystem().getControllerStateWithPose(1,
                                                                                          openvr.TrackingUniverseSeated,
                                                                                            )
    for i in pControllerState.rAxis:
        print(i.x, i.y)
```

I get only zeroes, am I doing something wrong?
(Edit - I had init inside loop)

**Comment by mdovgialo** [comment]
Some additional info. I'm running Windows 10, Python 3.5.3, openvr.__version__ == '1.0.0701'

**Comment by mdovgialo** [comment]
Got it working under openvr-1.0.301

**Comment by mdovgialo** [comment]
Under openvr-1.0.301 this works:
```
import openvr

openvr.init(openvr.VRApplication_Background)

while True:
    print()
    for c in range(16):
        result, pControllerState = openvr.VRSystem().getControllerState(c)
        for i in pControllerState.rAxis:
            if i.x != 0 or i.y != 0:
                print(i.x, i.y)

```

Under openvr-1.0.701
Now it works! I don't understand what's happening

**Comment by mdovgialo** [comment]
I see my error now, sorry for bothering you guys, I made a mistake and couldn't see it.

**Comment by kazoo-kmt** [comment]
Hi @mdovgialo, I'm having the similar issue. What was wrong with your code?

**Comment by mdovgialo** [comment]
I had function arguments mixed up.
As you can see: 
```
def getControllerStateWithPose(self, eOrigin, unControllerDeviceIndex, unControllerStateSize=sizeof(VRControllerState_t)):
```
the first one is the tracking universe id, the seconds is the device index and I did it vice versa.

But this function introduced a little lag in posing information, so I don't use it. You can see minimal example to get axis:
https://github.com/mdovgialo/steam-vr-wheel/blob/master/steam_vr_wheel/test.py

I've found, that it's better to get poses like that:

```
poses_t = openvr.TrackedDevicePose_t * openvr.k_unMaxTrackedDeviceCount
vrsystem.getDeviceToAbsoluteTrackingPose(openvr.TrackingUniverseSeated, 0, len(poses), poses)
```

And then get controller state for a controller:
```
result, pControllerState = vrsys.getControllerState(controller_id)
trigger = pControllerState.rAxis[1].x
trackpadX = pControllerState.rAxis[0].x
trackpadY = pControllerState.rAxis[0].y
```

Controller_id can be any number from 0 to 15, so you have to identify controllers using something like this:

```
def get_controller_ids():
    vrsys = openvr.VRSystem()
    for i in range(openvr.k_unMaxTrackedDeviceCount):
        device_class = vrsys.getTrackedDeviceClass(i)
        if device_class == openvr.TrackedDeviceClass_Controller:
            role = vrsys.getControllerRoleForTrackedDeviceIndex(i)
            if role == openvr.TrackedControllerRole_RightHand:
                 right = i
            if role == openvr.TrackedControllerRole_LeftHand:
                 left = i
return left, right
```

**Comment by kazoo-kmt** [comment]
I see. Thank you for your answer. I tried all the controller_id, but still get zero. I'm using SteamVR on Linux and that may cause the issue. Just noticed that pyopenvr had some issues to get the controller's state and I'm guessing it's not solved yet for the Linux environment. https://github.com/cmbruns/pyopenvr/issues/27

**Comment by stepjam** [comment]
Hi @kazoo-kmt, did you ever resolve this for linux?

**Comment by matEhickey** [comment]
~~~
vr_system = openvr.init(openvr.VRApplication_Background)
result, pControllerState = openvr.VRSystem().getControllerState(openvr.TrackedControllerRole_LeftHand)
trigger = pControllerState.rAxis[1].x
trackpadX = pControllerState.rAxis[0].x
trackpadY = pControllerState.rAxis[0].y
print("ok : "+str(result))
print("trigger : "+str(trigger))
print("trackpadX : "+str(trackpadX))
print("trackpadY : "+str(trackpadY))
~~~  
These value always remain at 0.0, except for result, that always stay at one, even if the controller is shutdown.  

(Windows 10, openvr 1.0.1201)
