### ISSUE TITLE
pyopenvr install issue

### ISSUE THREAD

**Issue by Noelok** [cmbruns/pyopenvr#33]
Hi, 
I tried to install pyopenvr using "_pip install pyopenvr_" on my windows pro 10 pc and I got this error message:
"_Could not find a version that satisfies the requirement pyopenvr (from versions: )
No matching distribution found for pyopenvr"_
Any ideas why? 
Thank you for your help!
Noel.

**Comment by cmbruns** [comment]
Try "pip install openvr"

**Comment by Noelok** [comment]
Thanks Christopher!
"pip install openvr" worked :)
Having openvr installed, do I still need to install pyopenvr?

**Comment by cmbruns** [comment]
No, you are done. "openvr" is the python module name. "pyopenvr" is the name of this github project, which contains the code for the openvr module, which wraps the openvr library in python.

**Comment by Noelok** [comment]
Perfect! Thank you Christopher! I really appreciate it :)
