### ISSUE TITLE
EVRButtonId is always 0(k_EButton_System)

### ISSUE THREAD

**Issue by kazoo-kmt** [cmbruns/pyopenvr#35]
While I keep running`pollNextEvent(event)`, `event.data.controller.button` or EVRButtonId is always zero even though I press different buttons. Am I missing something?

Regarding EVREventType, `event.eventType `shows 200 or VREvent_ButtonPress, which seems fine.

**Comment by kazoo-kmt** [comment]
Let me add the detail. Both pictures were taken when the Vive Controller's trigger is pulled. eventType shows the correct value, but the button id doesn't have the correct value.

![screenshot from 2017-06-27 09-54-45](https://user-images.githubusercontent.com/14499626/27600419-ba0aaf18-5b20-11e7-8455-342e0a29c68a.png)

![screenshot from 2017-06-27 09-55-12](https://user-images.githubusercontent.com/14499626/27600415-b6eced14-5b20-11e7-9379-fecd74cf8889.png)

**Comment by kazoo-kmt** [comment]
I guess this is related to the issue https://github.com/cmbruns/pyopenvr/issues/27 and this hasn't been solved for the VREvent_t struct. Please let me know if anyone has similar issues.

**Comment by kazoo-kmt** [comment]
https://github.com/cmbruns/pyopenvr/issues/27#issuecomment-313755407 temporary solves the problem.

**Comment by daniel5gh** [comment]
That's good to hear!

For a permanent solution we may need to add `_pack_ = 4` to the relevant structs when Linux or OSX. As opposed to the C# here in Python we can just to that and runtime when Linux or OSX, so we don't need such an elaborate solution using the union like in C#.

Judging from the "Terrible Hack" comments in https://github.com/ValveSoftware/openvr/blob/bcac1bfbe2be3c1ff37e4f62b8e412fcdf29248e/headers/openvr_api.cs I think these are `VRControllerState_t` and `VREvent_t`.

But looking at https://github.com/cmbruns/pyopenvr/blob/1c4fefe/src/translate/openvr_capi.h I see two more structs that are aligned on 4 bytes using `pragma pack` when Linux or OSX: `RenderModel_TextureMap_t` and `RenderModel_t`.

@cmbruns What do you think?

**Comment by cmbruns** [comment]
@daniel5gh thanks for the careful investigation. Do you have any ideas about how to design an automated unit test to determine whether these structures and methods are or are not working correctly? I won't be available to work on this at all for the next couple of weeks, unfortunately. Also I haven't got SteamVR working at all on linux nor OSX yet, so I am unable to test any of this myself.

I'm a bit confused about why openvr_api.cs contains hints about the packing of one set of structures (VREvent_t, VRControllerState_t), while openvr_capi.h hints about others (RenderModel_TextureMap_t and RenderModel_t).

**Comment by daniel5gh** [comment]
I don't know how to automate a test for this, but maybe we can add fixes on a case by case basis so at least those cases will work on Linux and MacOS?

Here is one PR for the [VRControllerState_t case](https://github.com/cmbruns/pyopenvr/pull/42).

**Comment by tomgoddard** [comment]
Here is a patch to openvr/__init__.py (version 1.0.1301) to add _pack_ = 4 to VREvent_t on Linux so that VR controller button press events have correct values for event.data.controller.button that identify which button is pressed.  The patch is the same as was done for VRControllerState_t in pyopenvr 1.0.1301.  I've tested this on CentOS 7 and Ubuntu 18.0.4.  I attach the patch as a zip file because GitHub will not accept attachments with suffix .patch.

[openvr_linux_button.patch.zip](https://github.com/cmbruns/pyopenvr/files/2520361/openvr_linux_button.patch.zip)

**Comment by tomgoddard** [comment]
Thanks for patching openvr for Linux so quickly!  I will be trying openvr on macOS next and will report if anything goes wrong.
