### ISSUE TITLE
Touchpad values

### ISSUE THREAD

**Issue by JonasDichelle** [cmbruns/pyopenvr#40]
Hi, love your work, it has helped me tremendously with my project.
I am currently trying to implement the touchpad into my script.
I was wondering if you were aware of a way to simply print the x and y values of the pad?
Maybe in a similar way to your sample script in the readme?
Any help would be appreciated.

**Comment by JonasDichelle** [comment]
I have tried:
`import sys
import time
import openvr

openvr.init(openvr.VRApplication_Scene)
track_t =  openvr.TrackedDevicePose_t * openvr.k_unMaxTrackedDeviceCount
track = track_t()
poses_t = openvr.VREvent_TouchPadMove_t * openvr.k_unControllerStateAxisCount
poses = poses_t()

for i in range(30):
    openvr.VRCompositor().waitGetPoses(track, len(track), None, 1)
    hmd_pose = poses[openvr.k_eControllerAxis_TrackPad]
    print(hmd_pose.fValueXRaw)
    sys.stdout.flush()
    time.sleep(0.2)

openvr.shutdown()`
but it just returns an empty value:
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

**Comment by JonasDichelle** [comment]
nevermind I figured it out thanks to @mdovgialo previous issue conserning the triggers:
#35 
`import openvr

openvr.init(openvr.VRApplication_Background)

while True:
    print()
    for c in range(16):
        result, pControllerState = openvr.VRSystem().getControllerState(c)
        for i in pControllerState.rAxis:
            if i.x != 0 or i.y != 0:
                print(i.x, i.y)`

this code now returns the acurate x/y values of the touchpad

  | never mind I figured it out thanks to @mdovgialo previous issue concerning the triggers: #35  `import openvr  openvr.init(openvr.VRApplication_Background)  while True:     print()     for c in range(16):         result, pControllerState = openvr.VRSystem().getControllerState(c)         for i in pControllerState.rAxis:             if i.x != 0 or i.y != 0:                 print(i.x, i.y)`  this code now returns the accurate x/y values of the touchpad | never mind I figured it out thanks to @mdovgialo previous issue concerning the triggers: #35  `import openvr  openvr.init(openvr.VRApplication_Background)  while True:     print()     for c in range(16):         result, pControllerState = openvr.VRSystem().getControllerState(c)         for i in pControllerState.rAxis:             if i.x != 0 or i.y != 0:                 print(i.x, i.y)`  this code now returns the accurate x/y values of the touchpad
-- | -- | --
never mind I figured it out thanks to @mdovgialo previous issue concerning the triggers: #35  `import openvr  openvr.init(openvr.VRApplication_Background)  while True:     print()     for c in range(16):         result, pControllerState = openvr.VRSystem().getControllerState(c)         for i in pControllerState.rAxis:             if i.x != 0 or i.y != 0:                 print(i.x, i.y)`  this code now returns the accurate x/y values of the touchpad

**Comment by JonasDichelle** [comment]
never mind I figured it out thanks to @mdovgialo previous issue concerning the triggers: #35  this code now returns the accurate x/y values of the touchpad:

`import openvr

openvr.init(openvr.VRApplication_Background)

while True:
    print()
    for c in range(16):
        result, pControllerState = openvr.VRSystem().getControllerState(c)
        for i in pControllerState.rAxis:
            if i.x != 0 or i.y != 0:
                print(i.x, i.y)
`

**Comment by stepjam** [comment]
Did you get this working on linux or windows?

**Comment by JonasDichelle** [comment]
I got it working on windows
