### ISSUE TITLE
problem in qt5 example

### ISSUE THREAD

**Issue by AdrianSchuetz** [cmbruns/pyopenvr#43]
Hi,

I have run into a weird problem trying out the examples provided by you. Running an example always gives the error message attached. 

> 
> Traceback (most recent call last):
>   File "C:\Users\VRLab\Anaconda3\lib\site-packages\openvr\glframework\qt5_app.py", line 52, in render_vr
>     self.paintGL()
>   File "C:\Users\VRLab\Anaconda3\lib\site-packages\openvr\glframework\qt5_app.py", line 47, in paintGL
>     self.renderer.render_scene()
>   File "C:\Users\VRLab\Anaconda3\lib\site-packages\openvr\gl_renderer.py", line 204, in render_scene
>     glBindFramebuffer(GL_FRAMEBUFFER, self.right_fb.fb)
>   File "C:\Users\VRLab\Anaconda3\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
>     baseOperation = baseOperation,
> OpenGL.error.GLError: GLError(
> 	err = 1282,
> 	description = b'invalid operation',

> 	baseOperation = glBindFramebuffer,
> 	cArguments = (GL_FRAMEBUFFER, 3)
> )

However, some such as wx dont mind the error whereas qt5 just refuses to work. I also attached the system information. If I run the example script line by line the error does not occur. 

[systeminfo.txt](https://github.com/cmbruns/pyopenvr/files/1758394/systeminfo.txt)
![errormessage](https://user-images.githubusercontent.com/36403942/36669040-b7473b5a-1af3-11e8-8e44-0b07819e69f8.PNG)

**Comment by matEhickey** [comment]
Hello, I'm having the same issue. 
Did you find a workaround ?

**Comment by AdrianSchuetz** [comment]
Hi,
the latest NVIDIA driver update fixed the problem for me. Now everything runs smooth.

**Comment by cmbruns** [comment]
I just had this same problem myself. Even though I already had the latest nvidia drivers (397.31). The problem resolved for me after I rebooted the computer, updated Steam and SteamVR, then power cycled the Vive controller box. I'm unsure which of those steps are necessary, except that power cycling that box at the end was required to bring my trackers back to life.
