### ISSUE TITLE
SetOverlayTransformTrackedDeviceRelative missing parameter

### ISSUE THREAD

**Issue by matEhickey** [cmbruns/pyopenvr#44]
Hello
Maybe I don't understand something, but I'm wondering why there is no **pmatTrackedDeviceToOverlayTransform** argument on the **SetOverlayTransformTrackedDeviceRelative**.   
See the original wiki documentation : https://github.com/ValveSoftware/openvr/wiki/IVROverlay::SetOverlayTransformTrackedDeviceRelative  
This argument should set a transform from the controller origin but is not here on the python binding: 
~~~
setOverlayTransformTrackedDeviceRelative(ulOverlayHandle, unTrackedDevice) method of openvr.IVROverlay instance
    Sets the transform to relative to the transform of the specified tracked device
~~~

It return an matrix, so should I manipulate this matrix to add an offset from the controller ? 
In this case I would assume that by default it should be on 0,0,0, but no overlay is showing on any controllers (and on any places).  

Maybe I also send a wrong deviceIndex to this function ? here is my simplified code:
~~~
def get_controller_ids(vrsys=None):
    left, right = None, None
    for i in range(openvr.k_unMaxTrackedDeviceCount):
        device_class = vrsys.getTrackedDeviceClass(i)
        if device_class == openvr.TrackedDeviceClass_Controller:
            role = vrsys.getControllerRoleForTrackedDeviceIndex(i)
            if role == openvr.TrackedControllerRole_RightHand:
                right = i
            if role == openvr.TrackedControllerRole_LeftHand:
                left = i
    return left, right


overlay=openvr.VROverlay()
res, ov = overlay.createOverlay(overlayKey, overlayTitle)
overlay.setOverlayFromFile(ov,texturePath)

overlay.showOverlay(ov)

# all of this works, it spawn my image on 0,0,0 absolute position.

left, right = get_controller_ids()
res = overlay.setOverlayTransformTrackedDeviceRelative(ov, openvr.c_ulong(right))
# this make my overlay disapear
~~~

I also would like to say that when my overlay is on relativetransform mode, the matrix returned by GetOverlayTransformTrackedDeviceRelative is full of 0, that I think is not normal.  

(in case, yes, I'm sure that both my controllers are functionnal, detected by steamvr, usable/trackable/powered on, I have the latest nvidia driver, that my function get_controller_ids work fine and didn't return None , etc )

**Comment by matEhickey** [comment]
Found the same behavior on setOverlayTransformAbsolute -> There is no transform relative to the origin 

> HmdMatrix34_t *pmatTrackingOriginToOverlayTransform - Transform relative to the specified tracking origin

~~~
import inspect

print(inspect.getargspec(openvr.VROverlay().setOverlayTransformTrackedDeviceRelative))
print(inspect.getargspec(openvr.VROverlay().setOverlayTransformAbsolute))
~~~

display:  
~~~
ArgSpec(args=['self', 'ulOverlayHandle', 'unTrackedDevice'], varargs=None, keywords=None, defaults=None)
ArgSpec(args=['self', 'ulOverlayHandle', 'eTrackingOrigin'], varargs=None, keywords=None, defaults=None)
~~~

Here the functions definition:
~~~cpp
VROverlayError SetOverlayTransformTrackedDeviceRelative( VROverlayHandle_t ulOverlayHandle, TrackedDeviceIndex_t unTrackedDevice, const HmdMatrix34_t *pmatTrackedDeviceToOverlayTransform )
~~~
~~~cpp
VROverlayError SetOverlayTransformAbsolute( VROverlayHandle_t ulOverlayHandle, TrackingUniverseOrigin eTrackingOrigin, const HmdMatrix34_t *pmatTrackingOriginToOverlayTransform )
~~~

**Comment by matEhickey** [comment]
I think I figured out what is the problem:
It's probably because the cpp to python translator assume pointers arguments as return value.  
There is an exception list where we can add arguments pointers that will stay arguments.  

I think we should add 2 lines for each function on [translate.pl](https://github.com/cmbruns/pyopenvr/blob/master/src/translate/translate.pl)  

~~~
$in_pointer_arguments{"IVROverlay::SetOverlayTransformTrackedDeviceRelative ::pmatTrackingOriginToOverlayTransform"} = "";
$in_pointer_arguments{"IVROverlay::SetOverlayTransformAbsolute ::pmatTrackingOriginToOverlayTransform"} = "";
~~~

to add them as required arguments, or 'in_pointer_arguments_as_pointers' and 'default_argument_values' if we can set it like this with a initialised value.  

I'll try that, but unsure that my plateform will accept this, (+ I litteraly never used perl before ), if I achieve to make it work I'll make a PR.

**Comment by cmbruns** [comment]
It sounds like you are on the right track here. I will try to incorporate this the next time I make a build (hopefully soonish). Unfortunately the process of going from that perl script to the final __init__.py is not fully automated; So you might want to wait until I find the time to update the bindings.

**Comment by matEhickey** [comment]
Yep I saw that, my modifications broke some functions, and didn't achieve to make what I wanted. But I found where to repair the bindings that I needed. 
Do you want me to make a PR for these ?

**Comment by cmbruns** [comment]
@matEhickey yes please make a PR if you updated the bindings and tested that they work for you. This way I would have a specific target when I update the bindings and/or perl script.

**Comment by cmbruns** [comment]
@matEhickey I just made a new release 1.0.1301 that incorporates your suggested change. Could you please test the new release when you get a chance, and report back here whether the issue is resolved?

**Comment by matEhickey** [comment]
Hello, these changes seems functionnals on my tests-cases. Thank you for that :)
