### ISSUE TITLE
Allow non-windows platforms (Mac and Linux)

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/pyopenvr#5]
- Include shared libraries for other platforms
- Detect 32-bit vs 64-bit python
- Dynamically define function pointer callback type

**Comment by cmbruns** [comment]
I did some dewindowsificiation in revision 5b9279d18ee83caebef22ad77d6d7e46432bff52, but I have not tested on Mac nor Linux.

**Comment by nemanja-rakicevic** [comment]
Hi! I am using on Ubuntu 14.04 and Python 2.7 and I've installed pyopenvr as instructed, but when I want to use it (import openvr), I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/openvr/__init__.py", line 26, in <module>
    _openvr = cdll.LoadLibrary(_openvr_lib_name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: openvr_api_64: cannot open shared object file: No such file or directory
`

I tried adding appropriate paths where the libraries are to the PYTHONPATH and even changing the .so name so it matches openvr_api_64.so, but it still doesn't work.

**Comment by cmbruns-hhmi** [comment]
Correct me if I'm wrong, but I think regular OpenVR might not be working on linux at the moment https://github.com/ValveSoftware/openvr/issues/213
If OpenVR is not working on linux, pyopenvr won't work either.
Are you able to run SteamVR on linux?

**Comment by nemanja-rakicevic** [comment]
Yeah, it was pretty much a hassle to make it work, but this guide explains it well: http://www.vronlinux.com/articles/adventures-with-openvr-and-the-vive-on-linux.8
The Steam and SteamVR are installed and even though SteamVR GUI doesn't run, OpenVR works, I manage to run the test examples as in the link.

So what are the shared object libraries that come with pyopenvr (libopenvr_api_64.so)? Also, could you please tell me what is this https://pypi.python.org/pypi/openvr exactly and how is it different from Valve's OpenVR

**Comment by nemanja-rakicevic** [comment]
Could you maybe tell me where can I find this "openvr_api_64" shared object file?

**Comment by nemanja-rakicevic** [comment]
Hello,

I managed to solve the problem. 

Namely, the directory where the "libopenvr_api_64.so" shared libraries are located has to be added to the $LD_LIBRARY_PATH. This can be done by typing 
`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib/python2.7/dist-packages/openvr"`
or adding it to the bottom of the ~/.bashrc file, if you're using bash.

Secondly, in order to be able to load the library using ctypes it has to be done as cdll.LoadLibrary("libopenvr_api_64.so"), i.e. using the .so extension.

I'll try to make a pull request on github.

Cheers!

**Comment by cmbruns-hhmi** [comment]
Thank you @nemanja-rakicevic for submitting pull request #22, which fixes the loading of the openvr shared library on linux, in revision cbf17c296c66b49240abd8e8bab16d07a79fefe8
Now that you got the shared library to load, I wonder whether you also succeeded in using the OpenVR API from pyopenvr? These python bindings for the OpenVR API are still a work in progress, so there are probably function calls that I have not tested and debugged that might not function correctly, even on Windows, where I have focused all my testing. I appreciate your effort to get pyopenvr working on linux, and I hope you will continue to contribute to this project and to this issue thread.

**Comment by nemanja-rakicevic** [comment]
No problem :)
I am looking into some basics to understand the API, starting with the test code from README.md
I had problems at first with the `openvr.init(openvr.VRApplication_Scene)` as it didn't recognise the HMD (HmdPresent error), but at one point it just started working, so I'm trying to figure it out now and test stuff.
If I find any problems I'll try to fix them and send updates on to the repository.

**Comment by abencomo** [comment]
Unless I'm missing something, openvr seems to generate only a 32-bit .dylib library so as a result I'm getting the error below when I try to run the sample code in the README.md 
----------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import openvr
  File "/usr/local/lib/python2.7/site-packages/openvr/__init__.py", line 35, in <module>
    raise ValueError("Libraries not available for this platform: " + platform.system())
ValueError: Libraries not available for this platform: Darwin
------------------------------------------------------

**Comment by eric-schleicher** [comment]
Bringing this up since I'm not able to navigate past related errors on x64 Ubuntu Linux 16.04 LTS.

I've sorted out getting pip3, setuptools to install the pyopenvr module successfully without error
in my case it's get installed with python 3.5 to `/usr/local/lib/python3.5/dist-packages/openvr-1.0.602a0-py3.5.egg/openvr`

I've added the LD_LIBRARY_PATH as mentioned in the above [comment](https://github.com/cmbruns/pyopenvr/issues/5#issuecomment-245012925)
`${LD_LIBRARY_PATH}:/usr/local/lib/python3.5/dist-packages/openvr-1.0.602a0-py3.5.egg/openvr`
 another view confirming that the `/usr/local/lib/python3.5/dist-packages/openvr-1.0.602a0-
py3.5.egg/openvr/libopenvr_api_64.so` file exists

![image](https://cloud.githubusercontent.com/assets/8261783/24899507/63663e1e-1e55-11e7-83d6-f6a84c12c933.png)

and the following error when trying to use pyopenvr from within the triad wrapper module
![image](https://cloud.githubusercontent.com/assets/8261783/24899557/93f4b268-1e55-11e7-9d0f-c7982d0c6aa8.png)

Something obvious that i'm missing?

**Comment by cmbruns-hhmi** [comment]
@eric-schleicher Here are some things you could try to help investigate this problem on your linux machine:

1. On the linux command line, type "ldd libopenvr_api_64.so", to reveal what libraries libopenvr depends on. Perhaps some secondary library is missing?
2. Try manually loading the library in python, perhaps using various setting for LD_LIBRARY_PATH
```python
  python -i
  >>> import ctypes
  >>> lib1 = ctypes.CDLL('/usr/local/lib/python3.5/dist-packages/openvr-1.0.602a0- py3.5.egg/openvr/libopenvr_api_64.so')
  >>> lib2 = ctypes.CDLL('libopenvr_api_64.so')
  >>> ctypes.cdll.LoadLibrary('libopenvr_api_64.so')

**Comment by kazoo-kmt** [comment]
Hi @cmbruns-hhmi, I'm using Ubuntu 16.04-LTS and have a trouble to use pyopenvr. When I ran `openvr.init(openvr.VRApplication_Scene)`, I always get `Segmentation fault (core dumped)` like this.
```
$ python hello.py 
OpenVR test program
Runtime is installed
Segmentation fault (core dumped)
```
Then, I followed the comment at https://github.com/cmbruns/pyopenvr/issues/5#issuecomment-293251146. The followings are the output I got. 

```
$ ldd ~/venv/lib/python3.5/site-packages/openvr/libopenvr_api_64.so
    linux-vdso.so.1 =>  (0x00007ffdf225a000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a16d0a000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a16b06000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4a16783000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4a16566000)
    /lib64/ld-linux-x86-64.so.2 (0x000055815cae1000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a1619c000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a15f85000)
```
```
$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> lib1 = ctypes.CDLL('~/venv/lib/python3.5/site-packages/openvr/libopenvr_api_64.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ~/venv/lib/python3.5/site-packages/openvr/libopenvr_api_64.so: cannot open shared object file: No such file or directory
```
I'm not sure what is the next step to move forward. Does the above output mean I have all the 
libraries but have some problems with the PATH?

**Comment by kazoo-kmt** [comment]
I also ran `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/user-name/venv/lib/python3.5/site-packages/openvr/libopenvr_api_64.so"`, but the result was same: `Segmentation fault (core dumped)` when running `openvr.init`.

**Comment by cmbruns** [comment]
@kazoo-kmt Are other non-python openvr apps working for you on your linux
computer?

**Comment by kazoo-kmt** [comment]
I'm running StreamVR in my Linux as well.

**Comment by cmbruns** [comment]
"Segmentation fault" does not sound like a link error to me. Can you identify the exact line in hello.py that triggers the segmentation fault? Unfortunately I have not yet got steamvr working on linux here. So I can provide advice, but not actual debugging on linux at the moment.

**Comment by kazoo-kmt** [comment]
It happened on the line15 `vr_system = openvr.init(openvr.VRApplication_Scene)`. I got `openvr.isRuntimeInstalled()` working.

**Comment by cmbruns** [comment]
You should definitely use SteamVR. I was just checking to make sure that you got SteamVR itself working correctly.

As I said, I'm not able to debug linux at the moment. Are you able to write and run a C or C++ program that would make these same calls?

**Comment by kazoo-kmt** [comment]
I have some progress. I made a mistake to set the path. I set `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/user-name/venv/lib/python3.5/site-packages/openvr/libopenvr_api_64.so"` but this should be `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/user-name/venv/lib/python3.5/site-packages/openvr"`. 

After modifying above, I got the following error.
```
>>> openvr.init(openvr.VRApplication_Scene)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user-name/venv/lib/python3.5/site-packages/openvr/__init__.py", line 5042, in init
    initInternal(applicationType)
  File "/home/user-name/venv/lib/python3.5/site-packages/openvr/__init__.py", line 5146, in initInternal
    _checkInitError(error.value)
  File "/home/user-name/venv/lib/python3.5/site-packages/openvr/__init__.py", line 5028, in _checkInitError
    raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
openvr.OpenVRError: b'VRInitError_Init_VRClientDLLNotFound' (error number 102)
```

**Comment by cmbruns** [comment]
At this point it's painful to use Linux, but it is working. Mac is no longer supported by Valve so Mac is probably off the list.
