### ISSUE TITLE
getControllerStateWithPose and getControllerState bugs the output of getDeviceToAbsoluteTrackingPose

### ISSUE THREAD

**Issue by mganglb** [cmbruns/pyopenvr#51]
setup:
Ubuntu: 16.04
Python: 2.7

Scenario:
SteamVR beta, (up2date)
Steam Beta, (up2date)
2 Mainstations with Sync cable (Mainstations are not up2date)
1 generic tracker (up2date)
No HMD (Null driver)

All works fine as long i do not use getControllerStateWithPose or getControllerState.

Using that functions changes the Transformation Matrix of getDeviceToAbsoluteTrackingPose (This change is only if the Tracker is in Motion and about 2 seconds after it stopped motion)

The setting of the origin do not has any influence on that effect. (TrackingUniverseSeated, TrackingUniverseRawAndUncalibrated, TrackingUniverseStanding)

The Origin has anyway no impact on the Pose of the tracker. But it impacts the pose of the controller.

best wishes
mganglb

**Comment by cmbruns** [comment]
@mganglb it sounds like you maybe found a solution to this issue at https://github.com/ValveSoftware/openvr/issues/883

Should this here issue be closed?

**Comment by mganglb** [comment]
@cmbruns Hello, yes i guess we can close it.
