### ISSUE TITLE
Problem with timing.m_nSize in getFrameTiming() function of IVRCompositor

### ISSUE THREAD

**Issue by lizbaka** [cmbruns/pyopenvr#97]
I am using `getFrameTiming()` in the class `IVRCompositor` to obtain frame timing information. 

In the official OpenVR API, this function receives a reference to an instance of `Compositor_FrameTiming` to be filled, and the documentation mentions that: 
> To maintain compatibility with previous versions, `Compositor_FrameTiming` must be set to the size of the struct being passed. 

This is also mentioned in the comment in the corresponding Python function. However, the Python function seems to directly create a new instance of `Compositor_FrameTiming` without setting the `m_nSize` field, nor providing methods to set the `m_nSize` outside of the function, possibly resulting in failing to acquire frame timing info. 

```python
# Starting at line 4566
def getFrameTiming(self, framesAgo=0):
    """
    Returns true if timing data is filled it.  Sets oldest timing info if nFramesAgo is larger than the stored history.
    Be sure to set timing.size = sizeof(Compositor_FrameTiming) on struct passed in before calling this function.
    """
    fn = self.function_table.getFrameTiming
    timing = Compositor_FrameTiming()
#    timing.m_nSize = sizeof(Compositor_FrameTiming)
    result = fn(byref(timing), framesAgo)
    return result, timing
```

After adding the commented line, it works perfectly for me. I suppose this function should set the `m_nSize`, or at least provide a method to allow setting this field outside of this function?

**Comment by cmbruns** [comment]
Thank you for investigating this! Your report is incisive and well written. Good work!

Your solution probably works well, but I think the most elegant solution might be to set the `m_nSize` attribute in the constructor of `Compositor_FrameTiming()`. This approach might solve the problem in both `getFrameTiming()` and in `getFrameTimings()`. (And a similar approach might be needed for `class DriverDirectMode_FrameTiming`)

Unfortunately is it not easy for me to test this at the moment. Would you please be willing to test an alternate solution for your case and let us know the results?

Please try something like below (sorry this is not tested; you might need to debug a little):

```python
# Around line 2391 of openvr/__init__.py

class Compositor_FrameTiming(Structure):
    """Provides a single frame's timing information to the app"""

    # Please try adding this constructor
    def __init__(self):
        super().__init__(sizeof(Compositor_FrameTiming))  # explicitly set m_nSize attribute

    _fields_ = [
        ("m_nSize", c_uint32),
        ...
```

Please also consider opening a [pull request](https://github.com/cmbruns/pyopenvr/pulls) for the changes to `__init__.py`. This way you would get credit as a "Contibutor" at https://github.com/cmbruns/pyopenvr/graphs/contributors. If you do that, I will then take care of fixing the generator code in translate/model.py so you don't have to worry about that part.

**Comment by lizbaka** [comment]
Sure! I will try to test this solution in my setup.

**Comment by lizbaka** [comment]
Sorry for the late reply. I made a futher modification based on your code by specifying the attribute, e.g., m_nSize to initialize:
```py
    def __init__(self):
        super().__init__(m_nSize = sizeof(Compositor_FrameTiming))
```

Here is how I tested the code snippets and the result.

1. Run SteamVR
2. Initialize a `VRApplication_Background` application
3. Acquire an instance of VR compositor with `openvr.VRCompositor()`, then call its `getFrameTiming()` function to obtain the calling result and the `Compositor_FrameTiming` struct
4. Print and dump all attributes of the FrameTiming struct
5. Wait for 1 second, then go back to step 3



Here is the dumped data before adding the constructor: [before.csv](https://github.com/user-attachments/files/17302680/before.csv)
```
call_result,m_HmdPose,m_flClientFrameIntervalMs,m_flCompositorIdleCpuMs,m_flCompositorRenderCpuMs,m_flCompositorRenderGpuMs,m_flCompositorRenderStartMs,m_flCompositorUpdateEndMs,m_flCompositorUpdateStartMs,m_flNewFrameReadyMs,m_flNewPosesReadyMs,m_flPostSubmitGpuMs,m_flPreSubmitGpuMs,m_flPresentCallCpuMs,m_flSubmitFrameMs,m_flSystemTimeInSeconds,m_flTotalRenderGpuMs,m_flTransferLatencyMs,m_flWaitForPresentCpuMs,m_flWaitGetPosesCalledMs,m_nFrameIndex,m_nNumDroppedFrames,m_nNumFramePresents,m_nNumMisPresented,m_nNumVSyncsReadyForUse,m_nNumVSyncsToFirstView,m_nReprojectionFlags,m_nSize
1,<openvr.TrackedDevicePose_t object at 0x000001A2132CECC0>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
1,<openvr.TrackedDevicePose_t object at 0x000001A2132CEDC0>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
1,<openvr.TrackedDevicePose_t object at 0x000001A2132CEE40>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
1,<openvr.TrackedDevicePose_t object at 0x000001A2132CED40>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
1,<openvr.TrackedDevicePose_t object at 0x000001A213319040>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
1,<openvr.TrackedDevicePose_t object at 0x000001A2133190C0>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0
......
```

And after adding the constructor, the dumped data looks like this: [after.csv](https://github.com/user-attachments/files/17302684/after.csv)
```
call_result,m_HmdPose,m_flClientFrameIntervalMs,m_flCompositorIdleCpuMs,m_flCompositorRenderCpuMs,m_flCompositorRenderGpuMs,m_flCompositorRenderStartMs,m_flCompositorUpdateEndMs,m_flCompositorUpdateStartMs,m_flNewFrameReadyMs,m_flNewPosesReadyMs,m_flPostSubmitGpuMs,m_flPreSubmitGpuMs,m_flPresentCallCpuMs,m_flSubmitFrameMs,m_flSystemTimeInSeconds,m_flTotalRenderGpuMs,m_flTransferLatencyMs,m_flWaitForPresentCpuMs,m_flWaitGetPosesCalledMs,m_nFrameIndex,m_nNumDroppedFrames,m_nNumFramePresents,m_nNumMisPresented,m_nNumVSyncsReadyForUse,m_nNumVSyncsToFirstView,m_nReprojectionFlags,m_nSize
1,<openvr.TrackedDevicePose_t object at 0x0000021642DAECC0>,9.177199363708496,0.0,0.4691000282764435,0.6878719925880432,11.010031700134277,13.445432662963867,10.980133056640625,-16.481735229492188,-20.747634887695312,0.03686399757862091,13.609888076782227,0.414900004863739,0.04110000282526016,15.795079334896803,14.334624290466309,0.0,0.19689999520778656,-36.17253494262695,473,0,1,1,7,10,4,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DAEDC0>,10.402899742126465,0.0,0.2508000135421753,0.5466240048408508,12.179731369018555,13.861632347106934,12.164532661437988,-18.86483383178711,-21.149335861206055,0.01929599978029728,9.403264045715332,0.39070001244544983,0.2078000009059906,16.813224934957255,9.969183921813965,0.0,5.786399841308594,-40.96753692626953,515,0,1,1,6,11,20,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DAEE40>,2.4672000408172607,0.0,0.2693999707698822,0.5426560044288635,12.259133338928223,14.00743293762207,12.243033409118652,-4.561934947967529,-5.977535247802734,0.017855999991297722,9.515135765075684,0.4219000041484833,0.11380000412464142,17.80727853493507,10.075647354125977,0.0,5.814999580383301,-27.722536087036133,556,0,1,1,7,11,20,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DAED40>,3.0355000495910645,0.0,0.39900001883506775,0.6599359512329102,12.118032455444336,14.095032691955566,12.105232238769531,-4.2917351722717285,-5.985334873199463,0.03360000252723694,10.98361587524414,0.4610000252723694,0.14090000092983246,18.825308735117815,11.677151679992676,0.0,5.625999927520752,-26.992534637451172,598,0,1,1,6,11,20,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DF9040>,2.791800022125244,0.0,0.2679999768733978,0.6555519700050354,12.200333595275879,14.15583324432373,12.184732437133789,-4.349735260009766,-6.6525349617004395,0.1720000058412552,10.831551551818848,0.4812999963760376,0.20109999179840088,19.843518535151148,11.659103393554688,0.0,5.600200176239014,-28.010334014892578,640,0,1,1,7,11,20,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DF90C0>,3.2544000148773193,0.0,0.25620001554489136,0.6527679562568665,11.893531799316406,14.178232192993164,11.878532409667969,-7.355034351348877,-9.475434303283691,0.01801600120961666,10.626431465148926,0.8303000330924988,0.14839999377727509,20.837419934493372,11.297215461730957,0.0,5.534799575805664,-30.547033309936523,681,0,1,1,7,12,20,192
1,<openvr.TrackedDevicePose_t object at 0x0000021642DF91C0>,2.5764000415802,0.0,0.27560001611709595,0.6108800172805786,2.6734323501586914,4.278232574462891,2.6589322090148926,-15.406734466552734,-17.22613525390625,0.0180479995906353,9.719552040100098,0.313400000333786,0.12019999325275421,21.898006334547112,10.348480224609375,0.0,3.287100076675415,-33.231937408447266,733,0,1,1,5,8,20,192
......
```

I also roughly compared the printed `m_flTotalRenderGpuMs` with the frame rendering time in the performance graph produced by SteamVR, and they seem to almost match. As a result, I think this code is working as expetecd.

It's worth mentioning that I actually tested this code without a normal set of VR devices since they are out of my possession for now. I instead used [this driver](https://github.com/r57zone/OpenVR-driver-for-DIY) to display the VR scene on my monitor and test the code. But I think this should also work just fine on regular VR devices.
